name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Docker Login
      env:
        DOCKER_USER : ${{ DOCKER_USER }}
        DOCKER_PASS : ${{ DOCKER_PASS }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag muratxsimsek/go-diabetes-core:${{ github.run_number }} --tag muratxsimsek/go-diabetes-core:snapshot        
    - name: Push Docker Image
      run: |
        docker push muratxsimsek/go-diabetes-core:${{ github.run_number }}
        docker push muratxsimsek/go-diabetes-core:snapshot

