name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2

    - name: Deploy to swarm
      uses: sagebind/docker-swarm-deploy-action@v2
      with:
        remote_host: ssh://root@161.35.222.124
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        args: stack deploy --compose-file docker-compose.yml diabetes        

